api/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^upload/$', views.upload),
]

auctions/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'auctions'
urlpatterns = [
    url(r'^character/(?P<region>us|eu)/(?P<realm>[^/]+)/(?P<character>\S+)/$', views.character, name='character'),
    url(r'^extra_pets/$', views.extra_pets, name='extra_pets'),
    url(r'^mine/$', views.mine, name='mine'),
    url(r'^missing/$', views.missing, name='missing'),
    url(r'^pets/$', views.pets, name='pets'),
]

auctions/models/auction.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

from core.fields import BigAutoField

# ---------------------------------------------------------------------------

class Auction(models.Model):
    SHORT_TIME = 0
    MEDIUM_TIME = 1
    LONG_TIME = 2
    VERY_LONG_TIME = 3

    TIME_CHOICES = (
        (SHORT_TIME, 'Short'),
        (MEDIUM_TIME, 'Medium'),
        (LONG_TIME, 'Long'),
        (VERY_LONG_TIME, 'Very Long'),
    )

    id = BigAutoField(primary_key=True)

    realm = models.ForeignKey('core.Realm', db_index=True, related_name='auctions', on_delete=models.CASCADE)
    auction_id = models.IntegerField(db_index=True)

    item_id = models.IntegerField()
    quantity = models.IntegerField()
    bid = models.BigIntegerField()
    buyout = models.BigIntegerField()
    time_left = models.SmallIntegerField(choices=TIME_CHOICES, default=0)

    owner = models.ForeignKey('auctions.CharacterName', db_index=False, on_delete=models.CASCADE)
    owner_realm = models.ForeignKey('core.Realm', db_index=False, related_name='+', on_delete=models.CASCADE)

    context = models.IntegerField()
    rand = models.IntegerField()
    seed = models.BigIntegerField()

    bonus_list = ArrayField(models.IntegerField(), default=list)
    # modifiers = ??? nfi what this is for

    pet_breed_id = models.IntegerField()
    pet_quality_id = models.IntegerField()
    pet_species_id = models.IntegerField()
    pet_level = models.IntegerField()

# ---------------------------------------------------------------------------

auctions/models/charactername.py
from django.db import models

# ---------------------------------------------------------------------------

class CharacterName(models.Model):
    name = models.CharField(max_length=16, db_index=True)

# ---------------------------------------------------------------------------

auctions/models/historytimestamp.py
from django.db import models

# ---------------------------------------------------------------------------

class HistoryTimestamp(models.Model):
    timestamp = models.DateTimeField()

# ---------------------------------------------------------------------------

auctions/models/realmhistory.py
from django.db import models

from core.fields import BigAutoField

# ---------------------------------------------------------------------------

class RealmHistory(models.Model):
    id = BigAutoField(primary_key=True)

    timestamp = models.ForeignKey('auctions.HistoryTimestamp', related_name='+', on_delete=models.CASCADE)

    realm = models.ForeignKey('core.Realm', db_index=True, related_name='+', on_delete=models.CASCADE)
    item_id = models.IntegerField(db_index=True)
    pet_species_id = models.IntegerField(db_index=True)

    amount = models.IntegerField()
    min_buyout = models.BigIntegerField()
    max_buyout = models.BigIntegerField()
    mean_buyout = models.BigIntegerField()
    median_buyout = models.BigIntegerField()

# ---------------------------------------------------------------------------

auctions/models/regionhistory.py
from django.db import models

from core.fields import BigAutoField

# ---------------------------------------------------------------------------

class RegionHistory(models.Model):
    id = BigAutoField(primary_key=True)

    timestamp = models.ForeignKey('auctions.HistoryTimestamp', related_name='+', on_delete=models.CASCADE)

    region = models.CharField(max_length=2, db_index=True)
    item_id = models.IntegerField(db_index=True)
    pet_species_id = models.IntegerField(db_index=True)

    amount = models.IntegerField()
    min_buyout = models.BigIntegerField()
    max_buyout = models.BigIntegerField()
    mean_buyout = models.BigIntegerField()
    median_buyout = models.BigIntegerField()

# ---------------------------------------------------------------------------

thing/models/character.py
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db import models

# ---------------------------------------------------------------------------

class Character(models.Model):
    bnetaccount = models.ForeignKey('core.BNetAccount', blank=True, null=True, related_name='characters', on_delete=models.SET_NULL)
    #bnetaccount = models.IntegerField(blank=True, null=True)
    tag = models.ForeignKey('CharacterTag', blank=True, null=True, on_delete=models.SET_NULL)
    guild = models.ForeignKey('Guild', blank=True, null=True, on_delete=models.SET_NULL)

    name = models.CharField(max_length=16)
    realm = models.ForeignKey('core.Realm', on_delete=models.CASCADE)
    cls = models.ForeignKey('core.CharacterClass', on_delete=models.CASCADE)
    race = models.ForeignKey('core.CharacterRace', on_delete=models.CASCADE)
    gender = models.SmallIntegerField(default=0)
    level = models.SmallIntegerField(default=1)
    thumbnail = models.CharField(max_length=128)

    honorable_kills = models.IntegerField(default=0)
    pvp_prestige = models.SmallIntegerField(default=0)
    pvp_level = models.SmallIntegerField(default=0)
    pvp_honor_current = models.SmallIntegerField(default=0)
    pvp_honor_max = models.SmallIntegerField(default=0)

    copper = models.BigIntegerField(default=0)
    flight_speed = models.SmallIntegerField(default=0)
    ground_speed = models.SmallIntegerField(default=0)
    played_total = models.IntegerField(default=0)
    played_level = models.IntegerField(default=0)
    garrison_level = models.SmallIntegerField(default=0)

    current_xp = models.IntegerField(default=0)
    level_xp = models.IntegerField(default=0)
    rested_xp = models.IntegerField(default=0)
    resting = models.BooleanField(default=False)

    keystone_id = models.SmallIntegerField(default=0)
    keystone_level = models.SmallIntegerField(default=0)
    keystone_max = models.SmallIntegerField(default=0)
    keystone_period = models.SmallIntegerField(default=0)

    hidden_dungeons = models.SmallIntegerField(default=0)
    hidden_kills = models.SmallIntegerField(default=0)
    hidden_world_quests = models.SmallIntegerField(default=0)
    
    balance_mythic15 = models.BooleanField(default=False)
    balance_unleashed_monstrosities = ArrayField(models.SmallIntegerField(), default=list)

    bigger_fish_to_fry = ArrayField(models.SmallIntegerField(), default=list)

    azerite_level = models.SmallIntegerField(default=0)
    azerite_current_xp = models.BigIntegerField(default=0)
    azerite_level_xp = models.BigIntegerField(default=0)
    azerite_essences = ArrayField(models.IntegerField(), default=list)

    # API
    count_404 = models.IntegerField(default=0)
    last_modified = models.IntegerField(default=0)
    # Worker backend
    last_api_update = models.DateTimeField(blank=True, null=True, db_index=True)
    # Character data
    last_char_update = models.DateTimeField(blank=True, null=True)
    # Item data
    last_bag_update = models.DateTimeField(blank=True, null=True)
    last_bank_update = models.DateTimeField(blank=True, null=True)
    last_void_update = models.DateTimeField(blank=True, null=True)
    # Misc data
    last_mount_update = models.DateTimeField(blank=True, null=True)
    last_pet_update = models.DateTimeField(blank=True, null=True)
    last_reputation_update = models.DateTimeField(blank=True, null=True)
    last_world_quest_update = models.DateTimeField(blank=True, null=True)
    # Garrison data
    last_building_update = models.DateTimeField(blank=True, null=True)
    last_cache_check = models.DateTimeField(blank=True, null=True)
    last_follower_update = models.DateTimeField(blank=True, null=True)
    last_mission_update = models.DateTimeField(blank=True, null=True)

    # -------------------------------------------------------------------------

    def get_thumbnail_url(self):
        region = self.realm.region
        return '//%s.battle.net/static-render/%s/%s' % (region, region, self.thumbnail)

    def get_copper(self):
        return self.copper % 100

    def get_silver(self):
        return (self.copper / 100) % 100

    def get_gold(self):
        return self.copper / 10000

    def get_money(self):
        rest, copper = divmod(self.copper, 100)
        gold, silver = divmod(rest, 100)

        parts = []
        if gold:
            parts.append('%dg' % (gold))
        if silver:
            parts.append('%ds' % (silver))
        if copper or not (gold or silver):
            parts.append('%dc' % (copper))

        return ' '.join(parts)

# ---------------------------------------------------------------------------

auctions/views.py
import functools
import operator

from django.contrib.auth.decorators import login_required
from django.db import connection
from django.db.models import Q
from django.http import Http404
from django.shortcuts import *

from auctions.models import Auction
from core.models import BattlePet, Item, Realm
from core.util import format_currency
from intapi.views import _get_bnetaccount

# ---------------------------------------------------------------------------

timeLeft = {
    0: '<30 mins',
    1: '0.5-2 hours',
    2: '2-12 hours',
    3: '12-48 hours',
}

# ---------------------------------------------------------------------------

def _get_good_auctions(auctions):
    if len(auctions) == 0:
        return auctions

    item_ids = set()
    pet_ids = set()
    for auction in auctions:
        if auction.pet_species_id > 0:
            pet_ids.add(auction.pet_species_id)
        else:
            item_ids.add(auction.item_id)

    items = Item.objects.in_bulk(item_ids)
    pets = {}
    for pet in BattlePet.objects.filter(species_id__in=pet_ids):
        pets[pet.species_id] = pet

    good_auctions = []
    for auction in auctions:
        auction.nice_bid = format_currency(auction.bid)
        auction.nice_buyout = format_currency(auction.buyout)
        auction.nice_time_left = timeLeft[auction.time_left]

        if auction.pet_species_id > 0:
            if auction.pet_species_id in pets:
                auction.pet = pets[auction.pet_species_id]
                auction.name = auction.pet.name
                good_auctions.append(auction)
        else:
            auction.item = items.get(auction.item_id)
            if auction.item is not None:
                auction.name = auction.item.name
                good_auctions.append(auction)

    good_auctions.sort(key=lambda a: a.name)

    return good_auctions

# ---------------------------------------------------------------------------

def character(request, region, realm, character):
    realms = list(Realm.objects.filter(Q(region=region, name=realm) | Q(region=region, slug=realm)))
    if len(realms) == 0:
        raise Http404

    auctions = Auction.objects.filter(
        owner_realm=realms[0],
        owner__name__iexact=character,
    ).prefetch_related(
        'owner',
    )

    good_auctions = _get_good_auctions(auctions)

    return render(
        request,
        'auctions/character.html',
        dict(
            realm=realms[0],
            character=character,
            auctions=good_auctions,
        ),
    )

# ---------------------------------------------------------------------------

@login_required
def extra_pets(request):
    return render(
        request,
        'auctions/extra_pets.html',
    )

# ---------------------------------------------------------------------------

@login_required
def mine(request):
    good_auctions = []

    bnetaccount = _get_bnetaccount(request)
    if bnetaccount is not None:
        filters = []
        for character in bnetaccount.characters.all():
            filters.append(Q(owner_realm=character.realm_id, owner__name=character.name))

        if len(filters) > 0:
            auctions = Auction.objects.filter(functools.reduce(operator.or_, filters)).prefetch_related('owner', 'owner_realm')
            good_auctions = _get_good_auctions(auctions)

    return render(
        request,
        'auctions/mine.html',
        dict(
            auctions=good_auctions,
        ),
    )

# ---------------------------------------------------------------------------

@login_required
def missing(request):
    realms = []

    bnetaccount = _get_bnetaccount(request)
    if bnetaccount is not None:
        realms = Realm.objects.filter(character__bnetaccount=bnetaccount).distinct().order_by('name')

    return render(
        request,
        'auctions/missing.html',
        dict(
            realms=realms,
        ),
    )

# ---------------------------------------------------------------------------

def pets(request):
    region = request.GET.get('region')
    pet_name = request.GET.get('pet_name')

    auctions = []
    pet = None
    if region is not None and pet_name is not None:
        try:
            pet = BattlePet.objects.get(name__iexact=pet_name)
        except:
            pass
        else:
            auctions = Auction.objects.filter(
                realm__region=region,
                pet_species_id=pet.species_id,
                buyout__gt=0,
            ).prefetch_related(
                'owner',
                'owner_realm',
            ).order_by(
                'buyout',
            )[:100]

            for auction in auctions:
                auction.nice_buyout = format_currency(auction.buyout)
                auction.nice_time_left = timeLeft[auction.time_left]

    return render(
        request,
        'auctions/pets.html',
        dict(
            auctions=auctions,
            pet=pet,
            region=region,
        ),
    )

# ---------------------------------------------------------------------------

templates/auctions/character.html
{% extends "base.html" %}

{% block title %}Auctions - Character{% endblock %}

{% block content %}
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h2 style="margin-top: 0;">Auctions for {{ realm.region|upper }} / {{ realm.name }} / {{ character }}</h2>

            {% if auctions %}
              <table class="table table-condensed table-hover table-striped auctions-table">
                <thead>
                  <tr>
                    <th colspan="2">Item</th>
                    <th>Level</th>
                    <th>Bid</th>
                    <th>Buyout</th>
                    <th>Time Left</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {% for auction in auctions %}
                    <tr>
                      <td class="auction-thing">
                        {% if auction.pet_species_id > 0 %}
                          <img src="/static/img/18/{{ auction.pet.icon }}.jpg" width="18" height="18">
                          <a href="//www.wowhead.com/npc={{ auction.pet.id }}" class="quality{{ auction.pet_quality_id }}">{{ auction.pet.name }}</a>
                        {% else %}
                          <img src="/static/img/18/{{ auction.item.icon }}.jpg" width="18" height="18">
                          <a href="//www.wowhead.com/item={{ auction.item_id }}" class="quality{{ auction.item.quality }}">{{ auction.item.name }}</a>
                        {% endif %}
                      </td>
                      <td class="auction-all">
                        {% if auction.pet_species_id > 0 %}
                          <a href="{% url 'auctions:pets' %}?region={{ realm.region }}&pet_name={{ auction.pet.name }}">[all]</a>
                        {% else %}
                        {% endif %}
                      </td>
                      <td class="auction-level">
                        {% if auction.pet_species_id > 0 %}
                          {{ auction.pet_level }}
                        {% else %}
                          {{ auction.item.item_level }}
                        {% endif %}
                      </td>
                      <td class="auction-price">{{ auction.nice_bid }}</td>
                      <td class="auction-price">{{ auction.nice_buyout }}</td>
                      <td class="auction-remaining">{{ auction.nice_time_left }}</td>
                      <td></td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            {% endif %}
          </div>
        </div>
      </div>
{% endblock %}

templates/auctions/extra_pets.html
{% extends "base.html" %}

{% block title %}Auctions - Extra Pets{% endblock %}

{% block extra_js %}<script type="text/javascript">WoWthing.auctions_extra_pets.onload();</script>{% endblock %}

{% block content %}
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h2 style="margin-top: 0;">Extra Pets</h2>
            <p>This page shows the current minimum buyout price for any extra pets you have (more than 1).</p>
          </div>
        </div>
      </div>

      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12">
            <table class="table table-condensed table-hover table-striped auctions-table" id="auctions-table">
              <tbody>
                <tr>
                  <td>Loading, please wait...</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
{% endblock %}

templates/auctions/mine.html
{% extends "base.html" %}

{% block title %}My Auctions{% endblock %}

{% block content %}
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h2 style="margin-top: 0;">My Auctions</h2>

            {% if auctions %}
              <table class="table table-condensed table-hover table-striped auctions-table">
                <thead>
                  <tr>
                    <th>Character</th>
                    <th>Realm</th>
                    <th colspan="2">Item</th>
                    <th>Level</th>
                    <th>Bid</th>
                    <th>Buyout</th>
                    <th>Time Left</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {% for auction in auctions %}
                    <tr>
                      <td class="auction-name">{{ auction.owner.name }}</td>
                      <td class="auction-realm">{{ auction.owner_realm.name }}</td>
                      <td class="auction-thing">
                        {% if auction.pet_species_id > 0 %}
                          <img src="/static/img/18/{{ auction.pet.icon }}.jpg" width="18" height="18">
                          <a href="//www.wowhead.com/npc={{ auction.pet.id }}" class="quality{{ auction.pet_quality_id }}">{{ auction.pet.name }}</a>
                        {% else %}
                          <img src="/static/img/18/{{ auction.item.icon }}.jpg" width="18" height="18">
                          <a href="//www.wowhead.com/item={{ auction.item_id }}" class="quality{{ auction.item.quality }}">{{ auction.item.name }}</a>
                        {% endif %}
                      </td>
                      <td class="auction-all">
                        {% if auction.pet_species_id > 0 %}
                          <a href="{% url 'auctions:pets' %}?region={{ auction.owner_realm.region }}&pet_name={{ auction.pet.name }}">[all]</a>
                        {% else %}
                        {% endif %}
                      </td>
                      <td class="auction-level">
                        {% if auction.pet_species_id > 0 %}
                          {{ auction.pet_level }}
                        {% else %}
                          {{ auction.item.item_level }}
                        {% endif %}
                      </td>
                      <td class="auction-price">{{ auction.nice_bid }}</td>
                      <td class="auction-price">{{ auction.nice_buyout }}</td>
                      <td class="auction-remaining">{{ auction.nice_time_left }}</td>
                      <td></td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            {% endif %}
          </div>
        </div>
      </div>
{% endblock %}

templates/auctions/missing.html
{% extends "base.html" %}

{% block title %}Auctions - Missing Pets/Mounts/Toys{% endblock %}

{% block extra_js %}<script type="text/javascript">WoWthing.auctions.onload();</script>{% endblock %}

{% block content %}
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h2 style="margin-top: 0;">Missing Mounts/Pets/Toys</h2>

            <p>This page will show you current auctions for mounts, pets, and toys that you haven't learned. The
               normal tabs show auctions on realms where you have characters (you can hide realms in Settings)
               while the "all realms" tabs show auctions on all realms in your region.</p>

            <ul class="nav nav-tabs" id="tab-links" role="tablist">
              <li><a href="#mounts-tab">Mounts</a></li>
              <li><a href="#mounts-all-tab">Mounts (all realms)</a></li>
              <li><a href="#pets-tab">Pets</a></li>
              <li><a href="#pets-all-tab">Pets (all realms)</a></li>
              <li><a href="#toys-tab">Toys</a></li>
              <li><a href="#toys-all-tab">Toys (all realms)</a></li>
              <li><a href="#settings-tab">&#9881; Settings</a></li>
            </ul>

            <div class="tab-content" id="tab-container">
              <div class="tab-pane" id="mounts-tab"></div>
              <div class="tab-pane" id="mounts-all-tab"></div>
              <div class="tab-pane" id="pets-tab"></div>
              <div class="tab-pane" id="pets-all-tab"></div>
              <div class="tab-pane" id="toys-tab"></div>
              <div class="tab-pane" id="toys-all-tab"></div>

              <div class="tab-pane" id="settings-tab">
                <h3>Ignore realms</h3>
                <ul class="list-unstyled">
                  {% for realm in realms %}
                  <label><input type="checkbox" class="settings-ignore" data-id="{{ realm.id }}"> {{ realm.name }}</label>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

templates/auctions/pets.html
{% extends "base.html" %}

{% block title %}Pet Auctions{% endblock %}

{% block content %}
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h2 style="margin-top: 0;">Pet Auctions</h2>

            <form action="" class="form-inline">
              <div class="form-group">
                <label for="input-region">Region</label>
                <select id="input-region" name="region" class="form-control">
                  <option value="us"{% if region == 'us' %} selected{% endif %}>US</option>
                  <option value="eu"{% if region == 'eu' %} selected{% endif %}>EU</option>
                </select>
              </div>
              <div class="form-group">
                <label for="input-pet-name">Pet name</label>
                <input id="input-pet-name" name="pet_name" type="text" class="form-control" placeholder="Pet name...">
              </div>
            </form>

            {% if auctions %}
              <h3 class="auction-pet-name">
                <a href="//www.wowhead.com/npc={{ pet.id }}"><img src="/static/img/36/{{ pet.icon }}.jpg"> {{ pet.name }}</a> auctions on {{ region|upper }} realms
              </h3>
              <table class="table table-condensed table-hover table-striped auctions-table">
                <tbody>
                  {% for auction in auctions %}
                    <tr>
                      <td class="auction-name"><a href="{% url 'auctions:character' auction.owner_realm.region auction.owner_realm.name auction.owner.name %}">{{ auction.owner.name }}</a></td>
                      <td class="auction-realm">{{ auction.owner_realm.name }}</td>
                      <td class="auction-level quality{{ auction.pet_quality_id }}">{{ auction.pet_level }}</td>
                      <td class="auction-price">{{ auction.nice_buyout }}</td>
                      <td class="auction-remaining">{{ auction.nice_time_left }}</td>
                      <td></td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
            {% endif %}
          </div>
        </div>
      </div>
{% endblock %}