api/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^upload/$', views.upload),
]

teams/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'teams'
urlpatterns = [
    url(r'^create/$', views.create, name='create'),

    url(r'^add_character/$', views.add_character, name='add_character'),
    url(r'^del_character/(?P<team_id>\d+)/(?P<member_id>\d+)/$', views.del_character, name='del_character'),
    url(r'^edit_roles/(?P<team_id>\d+)/$', views.edit_roles, name='edit_roles'),

    url(r'^(?P<key>[A-Za-z0-9]{,16})/$', views.view, name='view'),
]

teams/models/team.py
import random

from django.contrib.auth.models import User
from django.db import models

chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890'

# ---------------------------------------------------------------------------

class Team(models.Model):
    owner = models.ForeignKey(User, related_name='teams', on_delete=models.CASCADE)

    name = models.CharField(max_length=64)
    description = models.TextField()
    region = models.CharField(max_length=2)
    access_key = models.CharField(max_length=16)
    default_realm = models.ForeignKey('core.Realm', blank=True, null=True, on_delete=models.SET_NULL)

    def generate_access_key(self):
        self.access_key = ''.join(random.choice(chars) for i in range(16))

# ---------------------------------------------------------------------------

teams/models/teammember.py
from django.db import models

# ---------------------------------------------------------------------------

class TeamMember(models.Model):
    TANK_ROLE = 1
    HEAL_ROLE = 2
    MELEE_ROLE = 3
    RANGED_ROLE = 4

    ROLE_CHOICES = (
        (0, '-None-'),
        (1, 'Tank'),
        (2, 'Healer'),
        (3, 'Melee DPS'),
        (4, 'Ranged DPS'),
    )

    team = models.ForeignKey('teams.Team', related_name='members', on_delete=models.CASCADE)
    character = models.ForeignKey('thing.Character', related_name='teams', on_delete=models.CASCADE)

    primary_role = models.SmallIntegerField(choices=ROLE_CHOICES)
    secondary_role = models.SmallIntegerField(choices=ROLE_CHOICES)
    note = models.CharField(max_length=64)

# ---------------------------------------------------------------------------

teams/views.py
import json

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Max
from django.shortcuts import *
from django.urls import reverse

from core.models import Realm
from teams.models import *
from thing.models import Character, CharacterItem, CharacterMythicPlus

# ---------------------------------------------------------------------------

@login_required
def create(request):
    if not request.user.profile.raidgroups_enabled:
        raise PermissionDenied()

    if request.method == 'POST':
        team = Team(
            owner_id=request.user.id,
            region=request.POST.get('region', 'us'),
            name=request.POST.get('name', 'Unnamed raid group'),
            description=request.POST.get('description', ''),
        )
        default_realm = request.POST.get('default_realm', '')
        if default_realm.isdigit():
            team.default_realm_id = int(default_realm)
        team.generate_access_key()
        team.save()

        return redirect(reverse('teams:view', kwargs=dict(key=team.access_key)))

    return render(
        request,
        'teams/create.html',
    )

# ---------------------------------------------------------------------------

@login_required
def add_character(request):
    team = get_object_or_404(Team, pk=request.POST['team'])
    if team.owner == request.user:
        char = None
        char_name = request.POST['character'][:16].split()[0]
        try:
            char = Character.objects.get(realm=request.POST['realm'], name=char_name)
        except Character.DoesNotExist:
            char = Character(
                bnetaccount=None,
                guild=None,
                name=request.POST['character'][:16],
                realm_id=request.POST['realm'],
                level=10,
                race_id=7,# Gnome
                cls_id=3, # Hunter
                last_api_update=None,
            )
            char.save()

        try:
            rgm = TeamMember.objects.get(team=team, character=char)
        except TeamMember.DoesNotExist:
            rgm = TeamMember(
                team=team,
                character=char,
                primary_role=0,
                secondary_role=0,
                note=request.POST['note'][:64],
            )
            rgm.save()

    return redirect(reverse('teams:view', kwargs=dict(key=team.access_key)))

# ---------------------------------------------------------------------------

@login_required
def del_character(request, team_id, member_id):
    team = get_object_or_404(Team, pk=team_id)

    if team.owner == request.user:
        team.members.filter(pk=member_id).delete()

    return redirect(reverse('teams:view', kwargs=dict(key=team.access_key)))

# ---------------------------------------------------------------------------

@login_required
def edit_roles(request, team_id):
    team = get_object_or_404(Team, pk=team_id)

    if team.owner == request.user and request.method == 'POST':
        member_map = {}
        for member in TeamMember.objects.filter(team=team):
            member_map[member.id] = member

        chars = request.POST.get('changes', '').split(';')
        for char in chars:
            parts = [int(p) for p in char.split(',') if p.isdigit()]
            if len(parts) == 3 and parts[0] in member_map:
                member = member_map[parts[0]]
                if parts[1] in range(5):
                    member.primary_role = parts[1]
                if parts[2] in range(5):
                    member.secondary_role = parts[2]
                member.save(update_fields=['primary_role', 'secondary_role'])

    return redirect(reverse('teams:view', kwargs=dict(key=team.access_key)))

# ---------------------------------------------------------------------------

def view(request, key):
    team = get_object_or_404(Team, access_key=key)

    # Fetch data
    characters = {}
    members = []
    for rgm in team.members.prefetch_related('character').order_by('character__name'):
        char = rgm.character
        
        members.append(dict(
            id=rgm.id,
            primary_role=rgm.primary_role,
            secondary_role=rgm.secondary_role,
            note=rgm.note,
            character=dict(
                id=char.id,
                level=char.level,
                name=char.name,
                realm_id=char.realm_id,
                cls=char.cls_id,
                race=char.race_id,
                gender=char.gender,
                items=[],
                mythicplus={},
                azerite_level=char.azerite_level,
                keystone_max=char.keystone_max,
                keystone_period=char.keystone_period,
            )
        ))
        characters[members[-1]['character']['id']] = members[-1]['character']

    # bulk items
    ci_qs = CharacterItem.objects.filter(
        character__in=characters.keys(),
        location=CharacterItem.EQUIPPED_LOCATION,
    ).prefetch_related(
        'item',
    )
    
    items = {}
    for ci in ci_qs:
        characters[ci.character_id]['items'].append(dict(
            s=ci.slot,
            i=ci.item_id,
            l=ci.item_level or ci.item.item_level(characters[ci.character_id]['level']),
            q=ci.quality,
            c=ci.context,
            e=ci.extra,
        ))

        if ci.item_id not in items:
            items[ci.item_id] = dict(
                c=ci.item.cls,
                i=ci.item.icon,
                u=ci.item.upgrades,
            )

    # bulk mythic plus
    season_max = CharacterMythicPlus.objects.all().aggregate(Max('season'))['season__max']

    cmp_qs = CharacterMythicPlus.objects.filter(
        character__in=characters.keys(),
        season=season_max,
    ).order_by(
        '-in_time',
    )
    
    for cmplus in cmp_qs:
        characters[cmplus.character_id]['mythicplus'].setdefault(cmplus.dungeon_id, []).append(dict(
            level=cmplus.level,
            completed_at=cmplus.completed_at,
            duration=cmplus.duration,
            in_time=cmplus.in_time,
            affixes=cmplus.affixes,
        ))

    #members.sort(key=lambda m: (m['primary_role'], m['character']['name']))

    data = dict(
        items=items,
        members=members,
        team_id=team.id,
        region=team.region,
        default_realm=team.default_realm_id,
        owner=request.user.is_authenticated and request.user == team.owner,
    )

    return render(
        request,
        'teams/view.html',
        dict(
            json_data=json.dumps(data),
            team=team,
        ),
    )

# ---------------------------------------------------------------------------

templates/teams/create.html
{% extends "base.html" %}

{% block title %}Create Team{% endblock %}

{% block extra_js %}
    <script type="text/javascript">WoWthing.teams.create_onload();</script>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">Create Team</h2>
                        <form action="" method="POST">
                            {% csrf_token %}
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Region</label>
                                <div class="col-sm-2">
                                    <select id="region" class="form-control" name="region">
                                        <option value="us">US</option>
                                        <option value="eu">EU</option>
                                        <option value="kr">KR</option>
                                        <option value="tw">TW</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Default realm</label>
                                <div class="col-sm-2">
                                    <select id="realm" class="form-control" name="default_realm"></select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Name</label>
                                <div class="col-sm-4">
                                    <input class="form-control" type="text" name="name">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-sm-2 col-form-label">Description</label>
                                <div class="col-sm-10">
                                    <input class="form-control" type="text" name="description">
                                </div>
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-2"></div>
                                <div class="col-sm-10">
                                    <button type="submit" class="btn btn-primary">Create team</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/teams/view.html
{% extends "base.html" %}

{% block title %}{{ team.name }} - Teams{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        WoWthing.teams.data={{ json_data|safe }};
        WoWthing.teams.view_onload();
    </script>
{% endblock %}

{% block content %}
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <h2>[{{ team.region|upper }}] {{ team.name }}</h2>
            <p>{{ team.description }}</p>
          </div>
        </div>

        {% if user.is_authenticated and team.owner == user %}
        <div class="row">
          <div class="col-xs-12">
            <form action="{% url 'teams:add_character' %}" method="POST" class="form-inline team-form">
              {% csrf_token %}
              <input type="hidden" name="team" value="{{ team.id }}">
              <div class="form-group">
                <label for="input-realm">Realm</label>
                <select id="input-realm" name="realm" class="form-control"></select>
              </div>
              <div class="form-group">
                <label for="input-character">Character</label>
                <input id="input-character" name="character" placeholder="Character..." class="form-control">
              </div>
              <div class="form-group">
                <label for="input-note">Note</label>
                <input id="input-note" name="note" placeholder="Note..." class="form-control">
              </div>
              <button type="submit" class="btn btn-default">Add character</button>
            </form>
          </div>
          
          <div class"row">
            <div class="col-xs-12">
              <form action="{% url 'teams:edit_roles' team.id %}" method="POST">
                {% csrf_token %}
                <input id="input-edit-roles" name="changes" type="hidden" value="">
                <button type="submit" class="btn btn-primary">Save role changes</button>
              </form>
              <br>
            </div>
          </div>
        </div>
        {% endif %}

        <div class="row">
          <div class="col-xs-12 team-radios team-show">
            <span>Show:</span>
            <label class="radio-inline"><input type="radio" name="radio-show" class="js-radio-show" value="gear" checked> Gear</label>
            <label class="radio-inline"><input type="radio" name="radio-show" class="js-radio-show" value="mythicplus"> Mythic+</label>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 team-radios team-groupby">
            <span>Group by:</span>
            <label class="radio-inline"><input type="radio" name="radio-groupby" class="js-radio-groupby" value="none" checked> None</label>
            <label class="radio-inline"><input type="radio" name="radio-groupby" class="js-radio-groupby" value="class"> Class</label>
            <label class="radio-inline"><input type="radio" name="radio-groupby" class="js-radio-groupby" value="primaryrole"> Primary Role</label>
            <label class="radio-inline"><input type="radio" name="radio-groupby" class="js-radio-groupby" value="armortype"> Armor Type</label>
            <label class="radio-inline"><input type="radio" name="radio-groupby" class="js-radio-groupby" value="note"> Note</label>
            <!--<label class="radio-inline"><input type="radio" name="radio-groupby" class="js-radio-groupby" value="tier"> Tier Token</label>-->
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12 team-radios team-highlight">
            <span>Highlight:</span>
            <label class="radio-inline"><input type="radio" name="radio-highlight" class="js-radio-highlight" value="none" checked> None</label>
            <label class="radio-inline"><input type="radio" name="radio-highlight" class="js-radio-highlight" value="problems"> Problems</label>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12" id="team-box">
          </div>
        </div>
      </div>
{% endblock %}