api/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^upload/$', views.upload),
]

intapi/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'intapi'
urlpatterns = [
    url(r'^auctions/(?P<cat>mounts|pets|toys)/(?P<realms>all|mine)/$', views.auctions),
    url(r'^auctions/extra_pets/$', views.extra_pets),
    url(r'^dynamic_data/$', views.dynamic_data, name='dynamic_data'),
    url(r'^goldhistory/$', views.gold_history),
    url(r'^goldhistory/(?P<interval>[hdm])/(?P<period>[0-9a-z]+)/$', views.gold_history),
    url(r'^item_image/(?P<item_id>\d+)/(?P<size>\d+)/$', views.item_image),
    url(r'^leaderboards/$', views.leaderboards),
    #url(r'^userdata/(?P<user_id>\d+)/$', views.userdata),
    url(r'^userdata/(?P<code>[0-9A-Za-z]{16})/$', views.userdata_code, name='userdata_code'),
    url(r'^useritems/$', views.useritems),
]

thing/models/accountpet.py
from django.db import models

# ---------------------------------------------------------------------------

class AccountPet(models.Model):
    bnetaccount = models.ForeignKey('core.BnetAccount', on_delete=models.CASCADE)
    pet = models.ForeignKey('core.BattlePet', on_delete=models.CASCADE)

    favourite = models.BooleanField(default=False)
    guid = models.CharField(max_length=16)
    level = models.SmallIntegerField()
    name = models.CharField(max_length=64)
    quality = models.SmallIntegerField()

# ---------------------------------------------------------------------------

thing/models/character.py
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField
from django.db import models

# ---------------------------------------------------------------------------

class Character(models.Model):
    bnetaccount = models.ForeignKey('core.BNetAccount', blank=True, null=True, related_name='characters', on_delete=models.SET_NULL)
    #bnetaccount = models.IntegerField(blank=True, null=True)
    tag = models.ForeignKey('CharacterTag', blank=True, null=True, on_delete=models.SET_NULL)
    guild = models.ForeignKey('Guild', blank=True, null=True, on_delete=models.SET_NULL)

    name = models.CharField(max_length=16)
    realm = models.ForeignKey('core.Realm', on_delete=models.CASCADE)
    cls = models.ForeignKey('core.CharacterClass', on_delete=models.CASCADE)
    race = models.ForeignKey('core.CharacterRace', on_delete=models.CASCADE)
    gender = models.SmallIntegerField(default=0)
    level = models.SmallIntegerField(default=1)
    thumbnail = models.CharField(max_length=128)

    honorable_kills = models.IntegerField(default=0)
    pvp_prestige = models.SmallIntegerField(default=0)
    pvp_level = models.SmallIntegerField(default=0)
    pvp_honor_current = models.SmallIntegerField(default=0)
    pvp_honor_max = models.SmallIntegerField(default=0)

    copper = models.BigIntegerField(default=0)
    flight_speed = models.SmallIntegerField(default=0)
    ground_speed = models.SmallIntegerField(default=0)
    played_total = models.IntegerField(default=0)
    played_level = models.IntegerField(default=0)
    garrison_level = models.SmallIntegerField(default=0)

    current_xp = models.IntegerField(default=0)
    level_xp = models.IntegerField(default=0)
    rested_xp = models.IntegerField(default=0)
    resting = models.BooleanField(default=False)

    keystone_id = models.SmallIntegerField(default=0)
    keystone_level = models.SmallIntegerField(default=0)
    keystone_max = models.SmallIntegerField(default=0)
    keystone_period = models.SmallIntegerField(default=0)

    hidden_dungeons = models.SmallIntegerField(default=0)
    hidden_kills = models.SmallIntegerField(default=0)
    hidden_world_quests = models.SmallIntegerField(default=0)
    
    balance_mythic15 = models.BooleanField(default=False)
    balance_unleashed_monstrosities = ArrayField(models.SmallIntegerField(), default=list)

    bigger_fish_to_fry = ArrayField(models.SmallIntegerField(), default=list)

    azerite_level = models.SmallIntegerField(default=0)
    azerite_current_xp = models.BigIntegerField(default=0)
    azerite_level_xp = models.BigIntegerField(default=0)
    azerite_essences = ArrayField(models.IntegerField(), default=list)

    # API
    count_404 = models.IntegerField(default=0)
    last_modified = models.IntegerField(default=0)
    # Worker backend
    last_api_update = models.DateTimeField(blank=True, null=True, db_index=True)
    # Character data
    last_char_update = models.DateTimeField(blank=True, null=True)
    # Item data
    last_bag_update = models.DateTimeField(blank=True, null=True)
    last_bank_update = models.DateTimeField(blank=True, null=True)
    last_void_update = models.DateTimeField(blank=True, null=True)
    # Misc data
    last_mount_update = models.DateTimeField(blank=True, null=True)
    last_pet_update = models.DateTimeField(blank=True, null=True)
    last_reputation_update = models.DateTimeField(blank=True, null=True)
    last_world_quest_update = models.DateTimeField(blank=True, null=True)
    # Garrison data
    last_building_update = models.DateTimeField(blank=True, null=True)
    last_cache_check = models.DateTimeField(blank=True, null=True)
    last_follower_update = models.DateTimeField(blank=True, null=True)
    last_mission_update = models.DateTimeField(blank=True, null=True)

    # -------------------------------------------------------------------------

    def get_thumbnail_url(self):
        region = self.realm.region
        return '//%s.battle.net/static-render/%s/%s' % (region, region, self.thumbnail)

    def get_copper(self):
        return self.copper % 100

    def get_silver(self):
        return (self.copper / 100) % 100

    def get_gold(self):
        return self.copper / 10000

    def get_money(self):
        rest, copper = divmod(self.copper, 100)
        gold, silver = divmod(rest, 100)

        parts = []
        if gold:
            parts.append('%dg' % (gold))
        if silver:
            parts.append('%ds' % (silver))
        if copper or not (gold or silver):
            parts.append('%dc' % (copper))

        return ' '.join(parts)

# ---------------------------------------------------------------------------

thing/models/charactercooldown.py
from django.db import models

# ---------------------------------------------------------------------------

class CharacterCooldown(models.Model):
    character = models.ForeignKey('Character', on_delete=models.CASCADE)

    spell_id = models.IntegerField()
    expires = models.DateTimeField(blank=True, null=True)

# ---------------------------------------------------------------------------

thing/models/charactercurrency.py
from django.db import models

# ---------------------------------------------------------------------------

class CharacterCurrency(models.Model):
    character = models.ForeignKey('Character', related_name='currencies', on_delete=models.CASCADE)
    currency = models.ForeignKey('core.Currency', related_name='+', on_delete=models.CASCADE)

    total = models.IntegerField()
    total_max = models.IntegerField()
    week = models.IntegerField()
    week_max = models.IntegerField()

    last_updated = models.DateTimeField(blank=True, null=True)

# ---------------------------------------------------------------------------

thing/models/characterdata.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

from thing.models import Character

# ---------------------------------------------------------------------------

class CharacterData(models.Model):
    character = models.ForeignKey('thing.Character', related_name='data', on_delete=models.CASCADE)

    achievements = ArrayField(models.IntegerField(), default=list)
    achievements_timestamp = ArrayField(models.BigIntegerField(), default=list)
    criteria = ArrayField(models.IntegerField(), default=list)
    criteria_quantity = ArrayField(models.BigIntegerField(), default=list)

    mounts = ArrayField(models.IntegerField(), default=list)
    mounts_extra = ArrayField(models.IntegerField(), default=list)

    quests = ArrayField(models.IntegerField(), default=list)
    quests_extra = ArrayField(models.IntegerField(), default=list)
    quests_md5 = models.CharField(max_length=32, default='')

# ---------------------------------------------------------------------------
# Magical hook so this gets called when a new character is created
def create_characterdata(sender, instance, created, **kwargs):
    if created:
        CharacterData.objects.create(character=instance)

models.signals.post_save.connect(create_characterdata, sender=Character)

# ---------------------------------------------------------------------------

thing/models/characterfollower.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

# ---------------------------------------------------------------------------

class CharacterFollower(models.Model):
    character = models.ForeignKey('Character', on_delete=models.CASCADE)
    follower = models.ForeignKey('core.GarrisonFollower', on_delete=models.CASCADE)

    level = models.SmallIntegerField(default=0)
    quality = models.SmallIntegerField(default=0)
    current_xp = models.IntegerField(default=0)
    level_xp = models.IntegerField(default=0)
    item_level = models.SmallIntegerField(default=0)
    vitality = models.SmallIntegerField(default=0)
    max_vitality = models.SmallIntegerField(default=0)
    is_troop = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    abilities = ArrayField(models.SmallIntegerField(), default=list)
    equipment = ArrayField(models.SmallIntegerField(), default=list)

# ---------------------------------------------------------------------------

thing/models/characteritem.py
from django.db import models

# ---------------------------------------------------------------------------

class CharacterItem(models.Model):
    BAGS_LOCATION = 1
    BANK_LOCATION = 2
    VOID_STORAGE_LOCATION = 3
    EQUIPPED_LOCATION = 4
    REAGENT_BANK_LOCATION = 5

    LOCATION_CHOICES = (
        (BAGS_LOCATION, 'Bags'),
        (BANK_LOCATION, 'Bank'),
        (VOID_STORAGE_LOCATION, 'Void Storage'),
        (EQUIPPED_LOCATION, 'Equipped'),
        (REAGENT_BANK_LOCATION, 'Reagent Bank'),
    )

    character = models.ForeignKey('Character', related_name='items', on_delete=models.CASCADE)
    item = models.ForeignKey('core.Item', related_name='+', on_delete=models.CASCADE)
    item_level = models.SmallIntegerField(default=0)
    quality = models.SmallIntegerField(default=0)

    count = models.IntegerField()
    location = models.SmallIntegerField(choices=LOCATION_CHOICES)
    container = models.IntegerField(default=0)
    slot = models.IntegerField(default=0)
    context = models.SmallIntegerField(default=0)

    extra = models.CharField(max_length=255, default='')

# ---------------------------------------------------------------------------

thing/models/characterlockout.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

# ---------------------------------------------------------------------------

class CharacterLockout(models.Model):
    DIFFICULTY_CHOICES = (
        (0, "World boss"),
        (1, "5-player instance"),
        (2, "5-player heroic instance"),
        (3, "10-player raid"),
        (4, "25-player raid"),
        (5, "10-player heroic raid"),
        (6, "25-player heroic raid"),
        (7, "25-player raid finder"),
        (8, "Challenge mode"),
        (9, "40-player raid"),
        (11, "Heroic scenario"),
        (12, "Scenario"),
        (14, "10-30-player flexible raid"),
        (15, "10-30-player flexible heroic raid"),
        (16, "20-player mythic raid"),
        (17, "10-30-player flexible raid finder"),
        (23, "5-player mythic instance"),
        (24, "5-player timewalker instance"),
    )

    character = models.ForeignKey('Character', related_name='lockouts', on_delete=models.CASCADE)
    instance = models.ForeignKey('core.Instance', related_name='+', on_delete=models.CASCADE)

    bosses = ArrayField(models.CharField(max_length=40), default=list)
    bosses_killed = models.SmallIntegerField()
    bosses_max = models.SmallIntegerField()
    difficulty = models.SmallIntegerField(choices=DIFFICULTY_CHOICES)
    expires = models.DateTimeField(blank=True, null=True)
    locked = models.BooleanField(default=True)

# ---------------------------------------------------------------------------

thing/models/charactermission.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

# ---------------------------------------------------------------------------

class CharacterMission(models.Model):
    character = models.ForeignKey('Character', on_delete=models.CASCADE)
    mission = models.ForeignKey('core.GarrisonMission', on_delete=models.CASCADE)

    finishes = models.DateTimeField(blank=True, null=True)

# ---------------------------------------------------------------------------

thing/models/charactermythicplus.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

# ---------------------------------------------------------------------------

class CharacterMythicPlus(models.Model):
    character = models.ForeignKey('thing.Character', related_name='mythic_plus', on_delete=models.CASCADE)

    season = models.SmallIntegerField()
    dungeon_id = models.SmallIntegerField()
    level = models.SmallIntegerField()
    completed_at = models.IntegerField()
    duration = models.IntegerField()
    in_time = models.BooleanField()
    affixes = ArrayField(models.SmallIntegerField(), default=list)

    class Meta:
        unique_together = ('character', 'season', 'dungeon_id', 'in_time')

# ---------------------------------------------------------------------------

thing/models/characterprofession.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

# ---------------------------------------------------------------------------

class CharacterProfession(models.Model):
    PRIMARY_SKILL = 1
    SECONDARY_SKILL = 2
    SKILL_CHOICES = (
        (PRIMARY_SKILL, "Primary"),
        (SECONDARY_SKILL, "Secondary"),
    )

    character = models.ForeignKey('Character', related_name='professions', on_delete=models.CASCADE)
    profession = models.ForeignKey('core.Profession', on_delete=models.CASCADE)

    skill_type = models.SmallIntegerField(choices=SKILL_CHOICES)
    current_skill = models.SmallIntegerField()
    max_skill = models.SmallIntegerField()

    recipes = ArrayField(models.IntegerField(), default=list)

    class Meta:
        ordering = ['skill_type', 'id']

# ---------------------------------------------------------------------------

thing/models/characterreputation.py
from django.db import models

# ---------------------------------------------------------------------------

_level_modifiers = {
    7: 42000,
    6: 21000,
    5: 9000,
    4: 3000,
    3: 0,
    2: -3000,
    1: -6000,
    0: -42000,
}

class CharacterReputation(models.Model):
    character = models.ForeignKey('Character', related_name='reputations', on_delete=models.CASCADE)
    faction = models.ForeignKey('core.Faction', on_delete=models.CASCADE)

    level = models.SmallIntegerField()
    current = models.IntegerField()
    max_value = models.IntegerField()
    paragon_value = models.SmallIntegerField(default=0)
    paragon_max = models.SmallIntegerField(default=0)
    paragon_ready = models.BooleanField(default=False)

    def get_absolute(self):
        return self.current + _level_modifiers[self.level]

# ---------------------------------------------------------------------------

thing/models/charactertag.py
from django.contrib.auth.models import User
from django.db import models

# ---------------------------------------------------------------------------

class CharacterTag(models.Model):
    id = models.AutoField(primary_key=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    short_name = models.CharField(max_length=8)
    long_name = models.CharField(max_length=64)
    foreground_colour = models.CharField(max_length=6)
    background_colour = models.CharField(max_length=6)

# ---------------------------------------------------------------------------

thing/views/history.py
import os

from django.shortcuts import *

# ---------------------------------------------------------------------------

VERSION_FILE = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../version.txt'))

# ---------------------------------------------------------------------------

def history(request):
    versions = []
    header = None
    date = None
    entries = []
    for line in open(VERSION_FILE):
        line = line.strip()
        if header is None:
            header, date = line.rsplit(' - ', 1)
        elif line.startswith('---'):
            pass
        elif line == '':
            versions.append([header, date, entries])
            header = None
            date = None
            entries = []
        else:
            if line.startswith('*'):
                entries.append([line[2:], []])
            elif line.startswith('-'):
                entries[-1][1].append(line[2:])

    if header and entries:
        versions.append([header, date, entries])

    return render(
        request,
        'thing/history.html',
        dict(
            versions=versions,
        ),
    )

# ---------------------------------------------------------------------------

templates/thing/error.html
{% extends "base.html" %}

{% block title %}Error!{% endblock %}

{% block content %}
        <div class="container">
          <div class="page-header no-top-margin">
            <h1>{{ error_title }}</h1>
          </div>
          <div class="alert alert-danger">
            {{ error_text }}
          </div>
        </div>
{% endblock %}

templates/thing/history.html
{% extends "base.html" %}

{% block title %}Version History{% endblock %}

{% block content %}
      <div class="container">
{% for title, date, entries in versions %}
        <div class="row">
          <div class="col-xs-12 panel panel-default history-box">
            <h3>{{ title }} <span class="small">{{ date }}</span></h3>
            <ul>
  {% for entry, subentries in entries %}
              <li>{{ entry }}{% if not subentries %}</li>{% else %}<ul>
    {% for subentry in subentries %}
                <li>{{ subentry }}</li>
    {% endfor %}
              </ul></li>{% endif %}
  {% endfor %}
            </ul>
          </div>
        </div>
{% endfor %}
      </div>
{% endblock %}

templates/thing/home.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load thing_tags %}

{% block title %}{% if public %}{{ public_user.username }} - {% endif %}Home{% endblock %}

{% block extra_js %}
<script type="text/javascript">
</script>

<script type="text/javascript">
    const WoWthingState = {
        userdata_url: '{% url 'intapi:userdata_code' userdata_code %}',
    };

    WoWthing.home._public={{ public|lower }};
    WoWthing.home._anonymized={{ anonymized|lower }};
    WoWthing.home._user_id={{ user_id }};
    WoWthing.home._achievement_js='{% static 'js/achievements.min.js' %}';
    WoWthing.home._transmog_js='{% static 'js/transmog.min.js' %}';

    WoWthing.home.onload();
</script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-xs-12" id="home-errors"></div>
</div>

<div class="row home-row">
    <div class="col-sidebar">
        <div class="home-sidebar" id="home-sidebar">
            <div class="list-group">
                <a href="#overview" class="list-group-item js-sidebar">Overview</a>
                <a href="#achievements" class="list-group-item js-sidebar">Achievements<span id="badge-achievements" class="badge"></span></a>
                {% if not public %}
                <a href="#currencies" class="list-group-item js-sidebar">Currencies</a>
                {% endif %}
                <a href="#gear" class="list-group-item js-sidebar">Gear</a>
                {% if not public %}
                <a href="#gold_history" class="list-group-item js-sidebar">Gold history</a>
                <a href="#items" class="list-group-item js-sidebar">Items</a>
                <a href="#lockouts" class="list-group-item js-sidebar">Lockouts<span id="badge-lockouts" class="badge"></span></a>
                {% endif %}
                <a href="#progress" class="list-group-item js-sidebar">Progress</a>
                <a href="#reputations" class="list-group-item js-sidebar">Reputations</a>
            </div>

            <div class="list-group">
                <a href="#mounts" class="list-group-item js-sidebar">Mounts<span id="badge-mounts" class="badge"></span></a>
                <a href="#pets" class="list-group-item js-sidebar">Pets<span id="badge-pets" class="badge"></span></a>
                <a href="#toys" class="list-group-item js-sidebar">Toys<span id="badge-toys" class="badge"></span></a>
            </div>

            {% if not public %}
            <div class="list-group">
                <a href="#transmog" class="list-group-item js-sidebar">Transmog<span class="badge">WIP</span></a>
                <a href="#settings" class="list-group-item js-sidebar">Settings</a>
            </div>
            {% endif %}
        </div>{# home-sidebar #}
    </div>{# col-sidebar #}

    <div class="home-main col">
        <div id="home-loading" class="home-content">
            <p>Loading, please wait...</p>
        </div>{# home-loading #}

        <div id="home-content" class="home-content">
        </div>{# home-content #}

        {% if not public %}
        <div id="home-settings" class="home-content" style="display: none">
            <form id="home-settings-form" action="{% url 'home_settings' %}" method="POST">
                {% csrf_token %}
                <input id="home-settings-currencies-input" type="hidden" name="overview_show_currencies">
                <input id="home-settings-lockouts-input" type="hidden" name="overview_show_lockouts">

                <button type="submit" class="btn btn-primary">Save changes</button>

                <div class="row">
                    <div class="col settings-content">
                        {% for section, field_names in settings_form.sections.items %}
                            <div class="card card-body">
                                <fieldset>
                                    <legend>{{ section }}</legend>
                                    {% for field_name in field_names %}
                                        {{ settings_form|fieldget:field_name|bsfield }}
                                    {% endfor %}
                                </fieldset>
                            </div>
                        {% endfor %}

                        <div class="card card-body">
                            <fieldset>
                                <legend>{% trans 'Overview grouping' %}</legend>
                                <input class="form-control" type="text" name="overview_group" value="{{ overview_group }}">
                                <span class="form-text">
                                    Comma-separated list of things to use to group characters on the overview. Options are <code>realm</code>,
                                    <code>faction</code>, <code>tag</code>, <code>class</code>.
                                    <br><br>
                                    The default is <code>realm</code>.
                                </span>
                            </fieldset>
                        </div>

                        <div class="card card-body">
                            <fieldset>
                                <legend>{% trans 'Overview sort order' %}</legend>
                                <input class="form-control" type="text" name="overview_sort" value="{{ overview_sort }}">
                                <span class="form-text">
                                    Comma-separated list of things to use to sort characters on the overview. Options are <code>name</code>,
                                    <code>level</code>, <code>itemlevel</code>, prefixed with '-' for descending order (eg <code>-itemlevel</code>).
                                    <br><br>
                                    The default is <code>-level,name</code>.</span>
                            </fieldset>
                        </div>

                        <div class="card card-body">
                            <fieldset>
                                <legend>{% trans 'Overview currencies' %}</legend>
                                <p>Add currencies by searching for them and either pressing Enter or clicking the currency name. Reorder via drag-and-drop. Delete by clicking the <span class="icon-trash"></span> icons.</p>
                                <div class="input-group">
                                    <input id="home-settings-currency-search" class="form-control" type="text" placeholder="Search currencies...">
                                    <span class="input-group-append" data-tippy-content="Add to list">
                                        <span class="input-group-text icon-plus"></span>
                                    </span>
                                </div>
                                <ul id="home-settings-currencies" class="list-group"></ul>
                            </fieldset>
                        </div>

                        <div class="card card-body">
                            <fieldset>
                                <legend>{% trans 'Overview lockouts' %}</legend>
                                <p>Add instances by searching for them and either pressing Enter or clicking the instance name. Reorder via drag-and-drop. Delete by clicking the <span class="icon-trash"></span> icons.</p>
                                <div class="input-group">
                                    <input id="home-settings-lockout-search" class="form-control" type="text" placeholder="Search instances...">
                                    <span class="input-group-append" data-tippy-content="Add to list">
                                        <span class="input-group-text icon-plus"></span>
                                    </span>
                                </div>
                                <ul id="home-settings-lockouts" class="list-group"></ul>
                            </fieldset>
                        </div>

                        <div class="card card-body">
                            <fieldset>
                                <legend>{% trans 'Hide characters' %}</legend>
                                <div class="panel-group" id="home-settings-hide"></div>
                            </fieldset>
                        </div>
                    </div>{# col settings-content #}
                </div>{# row #}
            </form>
        </div>{# home-content settings #}
        {% endif %}
    </div>{# home-main #}
</div>{# row #}
{% endblock %}

templates/thing/my_account.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'My Account' %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">{% trans 'My Account' %}</h2>
                <table class="table table-striped table-bordered my-account-table">
                    <tbody>
                        <tr>
                            <td>{% trans 'API Key' %}</td>
                            <td class="my-account-api-key">
                                <button class="btn btn-primary" data-toggle="collapse" data-target="#api-key">{%  trans 'Toggle key' %}</button>
                                <span id="api-key" class="collapse">{{ api_key }}</span>
                                <form action="{% url 'regenerate_api_key' %}" method="POST" class="form-inline">
                                    {% csrf_token %}
                                    <button class="btn btn-danger" type="submit">{%  trans 'Regenerate key' %}</button>
                                </form>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/thing/oauth_delete.html
{% extends "base.html" %}

{% block title %}OAuth Delete{% endblock %}

{% block content %}
        <div class="container">
          <div class="page-header no-top-margin">
            <h1>OAuth Delete</h1>
          </div>
          <form>
            <input type="hidden" name="confirm" value="{{ confirm }}">
            <p>Are you sure you wish to delete Account #{{ account.id }} ({{ account.battletag }})?</p>
            <div class="checkbox">
              <label><input type="checkbox" name="delete_characters"> Delete all character data</label>
            </div>
            <button type="submit" class="btn btn-danger">Delete account</button>
            <a class="btn btn-success" href="{% url 'oauth' %}">Get me out of here!</a>
          </form>
        </div>
{% endblock %}

templates/thing/search.html
{% extends "base.html" %}

{% load thing_tags %}

{% block title %}Search{% endblock %}

{% block content %}
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <form class="form-horizontal search-form">
{% for field in form %}
  {{ field|bshfield:2 }}
{% endfor %}
              <div class="col-sm-offset-2">
                <button type="submit" class="btn btn-primary">Search</button>
              </div>
            </form>

{% if searched %}
            <table class="table table-condensed search-table">
              <tbody>
  {% for total, ci in items %}
                <tr>
                  <td class="search-character">{{ ci.character.name }}</td>
                  <td class="search-realm">{{ ci.character.realm.get_name }}</td>
                  <td class="search-location">{{ ci.get_location_display }}</td>
                  <td class="search-count">{{ total }}x</td>
                  <td class="search-item">
                    <a href="https://www.wowdb.com/items/{{ ci.item.id }}" class="quality{{ ci.item.quality }}"><img src="https://media.wowdb.com/icons/items/16/{{ ci.item.id }}.jpg" width="16" height="16">[{{ ci.item.name }}]</a>
                  </td>
                </tr>
  {% empty %}
                <tr>
                  <td colspan="5">No results found.</td>
                </tr>
  {% endfor %}
              </tbody>
            </table>
{% endif %}{# searched #}
          </div>
        </div>
      </div>
{% endblock %}
<img src="/static/img/18/{{ ci.item.icon }}.jpg" width="18" height="18">