api/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^upload/$', views.upload),
]

auctions/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'auctions'
urlpatterns = [
    url(r'^character/(?P<region>us|eu)/(?P<realm>[^/]+)/(?P<character>\S+)/$', views.character, name='character'),
    url(r'^extra_pets/$', views.extra_pets, name='extra_pets'),
    url(r'^mine/$', views.mine, name='mine'),
    url(r'^missing/$', views.missing, name='missing'),
    url(r'^pets/$', views.pets, name='pets'),
]

intapi/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'intapi'
urlpatterns = [
    url(r'^auctions/(?P<cat>mounts|pets|toys)/(?P<realms>all|mine)/$', views.auctions),
    url(r'^auctions/extra_pets/$', views.extra_pets),
    url(r'^dynamic_data/$', views.dynamic_data, name='dynamic_data'),
    url(r'^goldhistory/$', views.gold_history),
    url(r'^goldhistory/(?P<interval>[hdm])/(?P<period>[0-9a-z]+)/$', views.gold_history),
    url(r'^item_image/(?P<item_id>\d+)/(?P<size>\d+)/$', views.item_image),
    url(r'^leaderboards/$', views.leaderboards),
    #url(r'^userdata/(?P<user_id>\d+)/$', views.userdata),
    url(r'^userdata/(?P<code>[0-9A-Za-z]{16})/$', views.userdata_code, name='userdata_code'),
    url(r'^useritems/$', views.useritems),
]

teams/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'teams'
urlpatterns = [
    url(r'^create/$', views.create, name='create'),

    url(r'^add_character/$', views.add_character, name='add_character'),
    url(r'^del_character/(?P<team_id>\d+)/(?P<member_id>\d+)/$', views.del_character, name='del_character'),
    url(r'^edit_roles/(?P<team_id>\d+)/$', views.edit_roles, name='edit_roles'),

    url(r'^(?P<key>[A-Za-z0-9]{,16})/$', views.view, name='view'),
]

templates/base.html
{% load i18n %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}" type="text/css">

    <title>{% block title %}{% endblock %} | WoWthing</title>
{% block extra_head %}{% endblock %}
  </head>

  <body>
    <noscript>
      <div class="alert alert-danger">You appear to have JavaScript disabled. This site uses JavaScript to do pretty much everything!</div>
    </noscript>

    <nav class="navbar navbar-expand-md navbar-dark">
      <a class="navbar-brand" href="{% url 'index' %}">WoWthing</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav" id="nav-list">
  {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' username=user.username %}">{% trans 'Home' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'search' %}" class="nav-border-right">{% trans 'Search' %}</a>
          </li>
  {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="auctions-dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans 'Auctions' %}</a>
            <div class="dropdown-menu" aria-labelledby="auctions-dropdown">
              {#<li><a href="">{% 'Item Search' %}</a></li>#}
              <a class="dropdown-item" href="{% url 'auctions:pets' %}">{% trans 'Pet Search' %}</a>
  {% if user.is_authenticated %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'auctions:extra_pets' %}">{% trans 'Extra Pets' %}</a>
              <a class="dropdown-item" href="{% url 'auctions:missing' %}">{% trans 'Missing Mounts/Pets/Toys' %}</a>
              <a class="dropdown-item" href="{% url 'auctions:mine' %}">{% trans 'My Auctions' %}</a>
  {% endif %}
            </div>
          </li>
  {% if user.is_authenticated %}
    {% if user.profile.raidgroups_enabled or teams %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="teams-dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans 'Teams' %}</a>
            <div class="dropdown-menu" aria-labelledby="teams-dropdown">
      {% if user.profile.raidgroups_enabled %}
              <a class="dropdown-item" href="{% url 'teams:create' %}">{% trans 'Create a team' %}</a>
      {% endif %}
      {% if teams %}
        {% if user.profile.raidgroups_enabled %}
              <div class="dropdown-divider"></div>
        {% endif %}
        {% for team in teams %}
              <a class="dropdown-item" href="{% url 'teams:view' team.access_key %}">{{ team.name }}{% if team.owner == user %} [Owner]{% endif %}</a>
        {% endfor %}
      {% endif %}
            </div>
          </li>
    {% endif %}{# visibility check #}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'oauth' %}">{% trans 'Link Battle.net Account' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'upload' %}">{% trans 'Upload data' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'leaderboards' %}">{% trans 'Leaderboards' %}</a>
          </li>
  {% endif %}{# authed #}
        </ul>

  {% if user.is_authenticated %}
        <form class="form-inline" action="{% url 'search' %}" role="search">
          <input type="search" class="form-control" placeholder="{% trans 'Quick search' %}" name="find">
        </form>
  {%endif %}

        <ul class="navbar-nav" id="nav-right">
  {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="user-dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user-dropdown">
              <a class="dropdown-item" href="{% url 'my_account' %}">{%  trans 'My Account' %}</a>
              <a class="dropdown-item" href="{% url 'character_tags' %}">{% trans 'Manage character tags' %}</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
            </div>
          </li>
  {% else %}{# not authed #}
          <li>
            <a href="{% url 'login' %}">{% trans 'Login / Register' %}</a>
          </li>
  {% endif %}{# authed #}
        </ul>
      </div>{# navbar-collapse #}
    </nav>{# navbar #}

    <main role="main" class="content container-fluid">
      {% block content %}{% endblock %}
    </main>

{% block extra_stuff %}{% endblock %}

    <footer>
        <div>
            <span><a href="https://gitlab.com/groups/thing-engineering/wowthing/-/issues">{% trans 'BUGS/SUGGESTIONS' %}</a></span>
            <span>Stop by the <a href="https://discord.gg/4UkTT5y">Thing Engineering Discord</a>!</span>
        </div>
        <div>
            <span>World of Warcraft images &reg; or &trade; <a href="https://blizzard.com" rel="noopener" target="_blank">Blizzard Entertainment</a></span>
        </div>
    </footer>

    {% if debug %}
        <script type="text/javascript" src="{% static 'js/dev/handlebars-v2.0.0.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/oldlibs/jquery-3.3.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/oldlibs/moment-2.22.2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/oldlibs/html.sortable-0.1.6.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/lib/popper-1.15.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/lib/tippy-4.3.4.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/lib/bootstrap-4.3.1.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/lib/bootstrap3-typeahead.min.js' %}"></script>
    {% else %}
        <script type="text/javascript" src="{% static 'js/libs.min.js' %}"></script>
    {% endif %}

    <script type="text/javascript" src="{% url 'intapi:dynamic_data' %}"></script>

    {% if debug %}
        <script type="text/javascript" src="{% static 'js/wowthing/_onload.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wowthing/achievement.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wowthing/achievementcriteria.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wowthing/auctions.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wowthing/auctions_extra_pets.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wowthing/checkbox_buttons.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wowthing/home.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wowthing/leaderboards.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wowthing/oauth.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wowthing/teams.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/wowthing/util.js' %}"></script>
        <script type="text/javascript" src="{% static 'generated/data.js' %}"></script>
    {% else %}
        <script type="text/javascript" src="{% static 'js/wowthing.min.js' %}"></script>
    {% endif %}

{% block extra_js %}{% endblock %}

    <script type="text/javascript" src="https://static-azeroth.cursecdn.com/current/js/syndication/tt.js"></script>
  </body>
</html>